-- Your SQL goes here
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence INCREMENT BY 1 START WITH 1 MAXVALUE 9223372036854775807 NO CYCLE;

CREATE TABLE car (
  id SERIAL  PRIMARY KEY,
  vin TEXT NOT NULL,
  make TEXT NOT NULL,
  model TEXT NOT NULL,
  year INTEGER NOT NULL,
  color TEXT NOT NULL,
  price DECIMAL NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT diesel_manage_updated_at('car');
